# Generated by Django 4.2.16 on 2026-05-28 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order'], 'verbose_name': 'Slide Hero', 'verbose_name_plural': 'Slides Hero'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Témoignage', 'verbose_name_plural': 'Témoignages'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='session_key',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fas fa-fish', max_length=50, verbose_name='Icône Font Awesome'),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Note admin'),
        ),
        migrations.AddField(
            model_name='order',
            name='cgv_accepted',
            field=models.BooleanField(default=False, verbose_name='CGV acceptées'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Paiement à la livraison (Cash)'), ('waafi', 'Waafi Mobile'), ('cac', 'CAC Mobile'), ('dmoney', 'D-Money'), ('saba', 'Saba Mobile')], default='cash', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence transaction'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='transactions/', verbose_name='Capture de transaction'),
        ),
        migrations.AddField(
            model_name='order',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier/Zone'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL image externe'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=5, verbose_name='Commande min (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_info',
            field=models.TextField(blank=True, verbose_name='Info nutritionnelles'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, max_length=100, verbose_name='Saison'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_text',
            field=models.CharField(default='Découvrir', max_length=50),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_url',
            field=models.CharField(default='/produits/', max_length=200),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('processing', 'En préparation'), ('delivering', 'En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=6, verbose_name='Quantité (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=50, verbose_name='Stock (kg)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='Quartier/Zone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
