services:
  - type: web
    name: kaluun
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate --noinput && python manage.py import_from_old_db && gunicorn kaluun.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "kaluun.onrender.com,kaluundjib.com,www.kaluundjib.com"
      - key: SITE_URL
        value: "https://kaluundjib.com"
      - key: EMAIL_HOST_USER
        value: "kaluunexpresse@gmail.com"
      - key: KALUUN_EMAIL_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
